/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.saem.telas;

import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Josefino Komba
 */
public class TelaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktop = new javax.swing.JPanel();
        PanelCor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenCadastro = new javax.swing.JMenu();
        MenCadArea = new javax.swing.JMenuItem();
        MenCadCurso = new javax.swing.JMenuItem();
        MenCandid = new javax.swing.JMenu();
        MenUsuario = new javax.swing.JMenuItem();
        MenAjuda = new javax.swing.JMenu();
        MenAjudaSobre = new javax.swing.JMenuItem();
        MenOp = new javax.swing.JMenu();
        MenOpsair = new javax.swing.JMenuItem();

        setTitle("SIAEM");
        setBackground(new java.awt.Color(0, 102, 51));
        setForeground(new java.awt.Color(0, 153, 102));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        desktop.setBackground(new java.awt.Color(102, 153, 0));

        PanelCor.setBackground(new java.awt.Color(255, 255, 255));
        PanelCor.setForeground(new java.awt.Color(51, 102, 0));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/utilizadores.png"))); // NOI18N

        lblUsuario1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblUsuario1.setText("Usuário");
        lblUsuario1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUsuario1MouseClicked(evt);
            }
        });

        lblData.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblData.setText("Data");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("BEM-VINDO AO SIAEM-ALUNOS ");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/logotipo-da-escola-53434712.jpg"))); // NOI18N

        javax.swing.GroupLayout PanelCorLayout = new javax.swing.GroupLayout(PanelCor);
        PanelCor.setLayout(PanelCorLayout);
        PanelCorLayout.setHorizontalGroup(
            PanelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCorLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PanelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblData)
                    .addGroup(PanelCorLayout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCorLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCorLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(73, 73, 73))))
        );
        PanelCorLayout.setVerticalGroup(
            PanelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelCorLayout.createSequentialGroup()
                .addGroup(PanelCorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelCorLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblUsuario1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelCorLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addComponent(lblData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(72, 72, 72))
        );

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addGap(0, 736, Short.MAX_VALUE)
                .addComponent(PanelCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, desktopLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PanelCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        MenCadastro.setText("Cadastrar");

        MenCadArea.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenCadArea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/Notes (2).png"))); // NOI18N
        MenCadArea.setText(" Áreas");
        MenCadArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadAreaActionPerformed(evt);
            }
        });
        MenCadastro.add(MenCadArea);

        MenCadCurso.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        MenCadCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/Notes (2).png"))); // NOI18N
        MenCadCurso.setText("Cursos");
        MenCadCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenCadCursoActionPerformed(evt);
            }
        });
        MenCadastro.add(MenCadCurso);

        Menu.add(MenCadastro);

        MenCandid.setText("Consultar Candidaturas");

        MenUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/ficha1.jpg"))); // NOI18N
        MenUsuario.setText("Alunos  Inscritos");
        MenUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenUsuarioActionPerformed(evt);
            }
        });
        MenCandid.add(MenUsuario);

        Menu.add(MenCandid);

        MenAjuda.setText("Ajuda");
        MenAjuda.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenAjudaMouseClicked(evt);
            }
        });

        MenAjudaSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenAjudaSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/help.png"))); // NOI18N
        MenAjudaSobre.setText("Sobre");
        MenAjudaSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenAjudaSobreActionPerformed(evt);
            }
        });
        MenAjuda.add(MenAjudaSobre);

        Menu.add(MenAjuda);

        MenOp.setText("Opções");

        MenOpsair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_DOWN_MASK));
        MenOpsair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/exit (2).png"))); // NOI18N
        MenOpsair.setText("Sair");
        MenOpsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenOpsairActionPerformed(evt);
            }
        });
        MenOp.add(MenOpsair);

        Menu.add(MenOp);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1121, 785));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MenUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenUsuarioActionPerformed
        // TODO add your handling code here:
        ConsultarUsuario cons = new ConsultarUsuario();
        cons.setVisible(true);
        desktop.add(cons);
        
    }//GEN-LAST:event_MenUsuarioActionPerformed

    private void MenAjudaSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenAjudaSobreActionPerformed
        // Chamando a tela sobre:
        dispose();
        new TelaSobre().setVisible(true);
    }//GEN-LAST:event_MenAjudaSobreActionPerformed

    private void MenCadAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadAreaActionPerformed
        // As linhas abaixo abrem o form TelaCadastroAC no desktop:
        TelaCadastroAC cadastro = new TelaCadastroAC();
        cadastro.setVisible(true);
        desktop.add(cadastro);
    }//GEN-LAST:event_MenCadAreaActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // As linhas abaixo substituem a label lblData pela data actual ao inicializar o form
        
        Date data = new Date();
        DateFormat formatador = DateFormat.getDateInstance(DateFormat.SHORT);
        lblData.setText(formatador.format(data));
    }//GEN-LAST:event_formWindowActivated

    private void MenOpsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenOpsairActionPerformed
        // Exibe uma caixa de dialogo:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if(sair == JOptionPane.YES_OPTION){
            System.exit(0);
            
        }
        
    }//GEN-LAST:event_MenOpsairActionPerformed

    private void MenAjudaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenAjudaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_MenAjudaMouseClicked

    private void MenCadCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenCadCursoActionPerformed
        // TODO add your handling code here:
        TelaCadastroCurso cadastro = new TelaCadastroCurso();
        cadastro.setVisible(true);
        desktop.add(cadastro);
        
    }//GEN-LAST:event_MenCadCursoActionPerformed

    private void lblUsuario1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUsuario1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblUsuario1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenAjuda;
    private javax.swing.JMenuItem MenAjudaSobre;
    private javax.swing.JMenuItem MenCadArea;
    private javax.swing.JMenuItem MenCadCurso;
    public static javax.swing.JMenu MenCadastro;
    public static javax.swing.JMenu MenCandid;
    private javax.swing.JMenu MenOp;
    private javax.swing.JMenuItem MenOpsair;
    private javax.swing.JMenuItem MenUsuario;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel PanelCor;
    private javax.swing.JPanel desktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblUsuario1;
    // End of variables declaration//GEN-END:variables
}
