/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package br.com.saem.telas;

import java.sql.*;
import br.com.saem.dal.ModuloConexao;
import br.com.saem.model.Areacurso;
import br.com.saem.model.Curso;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Josefino Komba
 */
public class TelaCadastroAC extends javax.swing.JInternalFrame {

    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    DefaultTableModel tbModel;
    Areacurso ac = new Areacurso();
    Curso c = new Curso();

    /**
     * Creates new form TelaCadastroAC
     */
    public TelaCadastroAC() {
        conexao = ModuloConexao.Conector();
        initComponents();
        tbModel = new DefaultTableModel();
        CarregarTable(tbModel, tblConsultarArea);
    }

    public void CarregarTable(DefaultTableModel tbModelF, JTable tblFuncionario) {
        Connection conex = ModuloConexao.Conector();
        Object[] lista = new Object[2];
        Object[] columnNames = {"ID","Nome"};

        tbModelF.setColumnIdentifiers(columnNames);

        String sql = String.format("SELECT * FROM areaCurso");
        try ( Statement stmt = conex.createStatement()) {
            stmt.execute(sql);
            try ( ResultSet rs = stmt.executeQuery(sql)) {
                while (rs.next()) {
                    lista[1] = (rs.getString("NomeArea"));
                    lista[0] = (rs.getInt(1));
                    
                    tbModelF.addRow(lista);
                }
                tblFuncionario.setModel(tbModelF);
            }

        } catch (SQLException ex) {
            ex.printStackTrace();

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCriarArea = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnAddArea = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblConsultarArea = new javax.swing.JTable();
        btnApagarArea = new javax.swing.JButton();
        btnAlterarArea = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setPreferredSize(new java.awt.Dimension(709, 722));

        jLabel2.setText("Criar Áreas");

        txtCriarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCriarAreaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N

        btnAddArea.setText("Adicionar");
        btnAddArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddAreaActionPerformed(evt);
            }
        });

        tblConsultarArea.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblConsultarArea);

        btnApagarArea.setText("Remover");
        btnApagarArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApagarAreaActionPerformed(evt);
            }
        });

        btnAlterarArea.setText("Alterar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 509, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAddArea)
                                .addGap(91, 91, 91)
                                .addComponent(btnApagarArea)
                                .addGap(110, 110, 110)
                                .addComponent(btnAlterarArea))
                            .addComponent(txtCriarArea, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCriarArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnApagarArea)
                            .addComponent(btnAlterarArea)
                            .addComponent(btnAddArea)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(205, Short.MAX_VALUE))
        );

        setBounds(0, 0, 709, 722);
    }// </editor-fold>//GEN-END:initComponents

    private void txtCriarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCriarAreaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCriarAreaActionPerformed

    private void btnAddAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddAreaActionPerformed
        // TODO add your handling code here:
        Connection conex = ModuloConexao.Conector();

        try ( PreparedStatement stmt = conex.prepareStatement("INSERT INTO areaCurso(NomeArea) "
                + "VALUES (?) ")) {
            stmt.setString(1, txtCriarArea.getText());
            stmt.execute();
            JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
            System.out.println("Cad sucesso");
            txtCriarArea.setText(" ");
            tbModel = new DefaultTableModel();
            CarregarTable(tbModel, tblConsultarArea);

        } catch (SQLException ex) {

            ex.printStackTrace();
        }


    }//GEN-LAST:event_btnAddAreaActionPerformed

    private void btnApagarAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApagarAreaActionPerformed
        // TODO add your handling code here:
        //remover();

        Connection conex = ModuloConexao.Conector();
        int confirma = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover determinada Área?");
        if (confirma == JOptionPane.YES_NO_OPTION) {
            int a = tblConsultarArea.getSelectedRow();
            int area = (int) tblConsultarArea.getValueAt(a, 0);
            
            try ( PreparedStatement stmt = conex.prepareStatement("DELETE FROM curso WHERE IdArea = ? ")) {
                stmt.setInt(1, area);
                stmt.execute();
                System.out.println("Elim Curso com sucesso");
                

            } catch (SQLException ex) {

                ex.printStackTrace();
            }
            

            try ( PreparedStatement stmt = conex.prepareStatement("DELETE FROM siaem.areacurso WHERE IdArea = ? ")) {
                stmt.setInt(1, area);
                stmt.execute();
                JOptionPane.showMessageDialog(null, "Eliminado com sucesso");
                System.out.println("Elim sucesso");
                txtCriarArea.setText(" ");
                tbModel = new DefaultTableModel();
                CarregarTable(tbModel, tblConsultarArea);

            } catch (SQLException ex) {

                ex.printStackTrace();
            }
    }//GEN-LAST:event_btnApagarAreaActionPerformed

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddArea;
    private javax.swing.JButton btnAlterarArea;
    private javax.swing.JButton btnApagarArea;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblConsultarArea;
    private javax.swing.JTextField txtCriarArea;
    // End of variables declaration//GEN-END:variables
}
