/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.saem.telas;

import java.sql.*;
import br.com.saem.dal.ModuloConexao;
import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Josefino Komba
 */
public class TelaLogin extends javax.swing.JFrame {
    
    Connection conexao = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public void logar() {
        String sql = "select* from usuario where Nome=?and Senha=?";
        try {
            // as linhas a baixo preparam a consulta a BD em função do que foi digitado nas caixas e texto
            //O ? interroga é substituido pelo conteúdo das váriaveis
            pst = conexao.prepareStatement(sql);
            pst.setString(1, txt.getText());
            String captura = new String(txtS.getPassword());
            pst.setString(2, captura);
            //a linha abaixo executa a query(consulta)
            rs = pst.executeQuery();
            //se existir um usuário e senha correspondente
            if (rs.next()) {
                // abaixo obtenhe o conteúdo do campo TipoUsuario da tabela usuario
                String TipoUsuario = rs.getString(3);
                // a linha abaixo verifica se está tudo certo
                //System.out.println(TipoUsuario);
                // a extrutura abaio faz o tratamento do perfil
                if (TipoUsuario.equals("Administrador")) {
                     new TelaPrincipal().setVisible(true);
                    
                    TelaPrincipal.lblUsuario1.setText(rs.getString(1));
                    TelaPrincipal.lblUsuario1.setForeground(Color.red);
                    this.dispose();
                    conexao.close();
                }else if(TipoUsuario.equals("Normal")){
                    new TelaPrincipalUsuario(rs.getString(2)).setVisible(true);
                       TelaPrincipalUsuario.lblUser.setText(rs.getString(1));

                    this.dispose();
                }
            } else {
                JOptionPane.showMessageDialog(null, "Usuário e/ou Senha inválido(s)\n Tente Novamente!");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }

    /**
     * Creates new form TelaLogin
     */
    public TelaLogin() {
        initComponents();
        conexao = ModuloConexao.Conector();
        // A linha a baixo apoia o status da conexão
        System.out.println(conexao);
        if (conexao != null) {
            lblStatus.setText("Conectado");
            
        } else {
            lblStatus.setText("Não conectado!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();
        txtS = new javax.swing.JPasswordField();
        lblStatus = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnCriarC = new javax.swing.JButton();
        btnDeixar = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SIAEM-ALUNOS");
        setBackground(new java.awt.Color(255, 255, 255));
        setForeground(new java.awt.Color(242, 242, 242));
        setIconImage(getIconImage());
        setMinimumSize(new java.awt.Dimension(660, 496));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Usuário");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 70, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Senha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 60, 40));
        jPanel1.add(txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 30, 260, 60));

        btnLogin.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, -1, -1));

        txtS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSActionPerformed(evt);
            }
        });
        jPanel1.add(txtS, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 260, 60));

        lblStatus.setText("Status");
        jPanel1.add(lblStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 470, 63, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 153, 0));
        jLabel9.setText("LICEU-NGS");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 80, 30));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/logotipo-da-escola-53434712.jpg"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 0, 210, 210));

        btnCriarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/add_user.png"))); // NOI18N
        btnCriarC.setToolTipText("Criar Conta");
        btnCriarC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCriarC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCriarCActionPerformed(evt);
            }
        });
        jPanel1.add(btnCriarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 440, 60, 40));

        btnDeixar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/saem/icones/button_cancel.png"))); // NOI18N
        btnDeixar.setToolTipText("Sair");
        btnDeixar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDeixar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeixarActionPerformed(evt);
            }
        });
        jPanel1.add(btnDeixar, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 440, 60, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 660, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here: chamando o método logar
        logar();
        txt.setText("");
        txtS.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSActionPerformed

    private void btnDeixarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeixarActionPerformed
        // Apresenta a caixa de dialogo Sair:
        int deixar = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja sair?", "Atenção!", JOptionPane.YES_NO_OPTION);
        if(deixar == JOptionPane.YES_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_btnDeixarActionPerformed

    private void btnCriarCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarCActionPerformed
        // TODO add your handling code here:
        dispose();
        new CriarConta().setVisible(true);
        
    }//GEN-LAST:event_btnCriarCActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCriarC;
    private javax.swing.JButton btnDeixar;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JTextField txt;
    private javax.swing.JPasswordField txtS;
    // End of variables declaration//GEN-END:variables
}
